// Server-side question database for the multiplayer game.
// Each question: { module, difficulty, q, code?, options, correct, exp }

const MODULES = {
  general:  { name: 'Data Analysis Basics', emoji: '🎯' },
  python:   { name: 'Python',               emoji: '🐍' },
  numpy:    { name: 'NumPy',                emoji: '🔢' },
  pandas:   { name: 'Pandas',               emoji: '🐼' },
  cleaning: { name: 'Data Cleaning',        emoji: '🧹' },
  viz:      { name: 'Visualization',        emoji: '📊' },
  stats:    { name: 'Statistics',           emoji: '📈' },
  ml:       { name: 'Machine Learning',     emoji: '🤖' }
};

const QUESTIONS = [
  // ===== GENERAL =====
  { module: 'general', difficulty: 'easy',
    q: 'Which is a STRUCTURED data format?',
    options: ['MP3 audio', 'SQL table', 'A Tweet', 'Image of cat'], correct: 1,
    exp: 'SQL tables have rigid rows/columns — textbook structured data.' },
  { module: 'general', difficulty: 'easy',
    q: 'What type of analysis answers "What happened?"',
    options: ['Predictive', 'Descriptive', 'Diagnostic', 'Prescriptive'], correct: 1,
    exp: 'Descriptive = what happened. Diagnostic = why. Predictive = what next. Prescriptive = what to do.' },
  { module: 'general', difficulty: 'medium',
    q: 'JSON data is classified as:',
    options: ['Structured', 'Semi-structured', 'Unstructured', 'Binary'], correct: 1,
    exp: 'JSON has hierarchy (key-value pairs) but no rigid schema — semi-structured.' },
  { module: 'general', difficulty: 'medium',
    q: 'How much of an analyst\'s time is typically spent cleaning data?',
    options: ['10-20%', '30-40%', '50-60%', '70-80%'], correct: 3,
    exp: 'Industry surveys: ~70-80% goes to data prep. Actual modeling is the quick part.' },
  { module: 'general', difficulty: 'hard',
    q: 'Which role focuses on building data PIPELINES?',
    options: ['Data Analyst', 'Data Engineer', 'Data Scientist', 'BI Analyst'], correct: 1,
    exp: 'Data Engineers build the pipes — ETL, warehouses, infrastructure.' },

  // ===== PYTHON =====
  { module: 'python', difficulty: 'easy',
    q: 'How to create a list in Python?',
    options: ['list = (1,2,3)', 'list = [1,2,3]', 'list = {1,2,3}', 'list = <1,2,3>'], correct: 1,
    exp: 'Square brackets = list. () = tuple. {} = set or dict.' },
  { module: 'python', difficulty: 'easy',
    q: 'What does len("hello") return?',
    options: ['4', '5', '6', 'Error'], correct: 1,
    exp: '"hello" has 5 characters.' },
  { module: 'python', difficulty: 'easy',
    code: 'x = [1, 2, 3]\nx.append(4)\nprint(x)',
    q: 'What prints?',
    options: ['[1,2,3]', '[1,2,3,4]', '[4,1,2,3]', '4'], correct: 1,
    exp: 'append() adds to the end and modifies the list in place.' },
  { module: 'python', difficulty: 'medium',
    code: 'nums = [1,2,3,4,5]\nprint(nums[1:4])',
    q: 'Output?',
    options: ['[1,2,3]', '[2,3,4]', '[2,3,4,5]', '[1,2,3,4]'], correct: 1,
    exp: '[start:stop] — start inclusive, stop exclusive.' },
  { module: 'python', difficulty: 'medium',
    q: 'Which collection has only UNIQUE items?',
    options: ['list', 'tuple', 'set', 'dict'], correct: 2,
    exp: 'Sets dedupe automatically.' },
  { module: 'python', difficulty: 'hard',
    code: 'sq = [x**2 for x in range(5) if x % 2 == 0]\nprint(sq)',
    q: 'Output?',
    options: ['[0,1,4,9,16]', '[0,4,16]', '[1,9]', '[2,4]'], correct: 1,
    exp: 'Keep only even x (0,2,4), then square → [0,4,16].' },
  { module: 'python', difficulty: 'medium',
    code: 'a = [1,2,3]\nb = a\nb.append(4)\nprint(a)',
    q: 'Output?',
    options: ['[1,2,3]', '[1,2,3,4]', '[4]', 'Error'], correct: 1,
    exp: 'b = a does NOT copy. Both names point to the same list.' },

  // ===== NUMPY =====
  { module: 'numpy', difficulty: 'easy',
    q: 'Standard NumPy import?',
    options: ['import numpy', 'import numpy as n', 'import numpy as np', 'from numpy import *'], correct: 2,
    exp: '"import numpy as np" — universal convention.' },
  { module: 'numpy', difficulty: 'easy',
    code: 'a = np.array([1,2,3])\nprint(a.shape)',
    q: 'Output?',
    options: ['3', '(3,)', '(1,3)', '[3]'], correct: 1,
    exp: '1D array of length 3 has shape (3,).' },
  { module: 'numpy', difficulty: 'medium',
    code: 'a = np.array([1,2,3])\nb = np.array([10,20,30])\nprint(a+b)',
    q: 'Output?',
    options: ['[1,2,3,10,20,30]', '[11,22,33]', 'Error', '[10,40,90]'], correct: 1,
    exp: 'NumPy arrays add ELEMENT-WISE, not concatenate.' },
  { module: 'numpy', difficulty: 'medium',
    q: 'sum(axis=0) on a 2D array returns:',
    options: ['Total sum', 'Sum per row', 'Sum per column', 'Cumulative sum'], correct: 2,
    exp: 'axis=0 collapses ROWS → one value per COLUMN. Counterintuitive!' },
  { module: 'numpy', difficulty: 'medium',
    code: 'a = np.array([1,2,3,4,5])\nprint(a[a>3])',
    q: 'Output?',
    options: ['[T,T]', '[4,5]', '[3,4,5]', 'Error'], correct: 1,
    exp: 'Boolean mask keeps elements where the condition is True.' },
  { module: 'numpy', difficulty: 'hard',
    q: 'Broadcasting works when:',
    options: ['Shapes are equal only', 'Shapes are compatible', 'Any shapes', 'Only same dtype'], correct: 1,
    exp: 'Dimensions match if equal OR one is 1. (2,3)+(3,) works.' },

  // ===== PANDAS =====
  { module: 'pandas', difficulty: 'easy',
    q: 'A Pandas Series is most like:',
    options: ['A dict', '1D labeled array', '2D table', 'A tuple'], correct: 1,
    exp: 'Series = 1D labeled array — one column with an index.' },
  { module: 'pandas', difficulty: 'easy',
    q: 'How to read a CSV in Pandas?',
    options: ['pd.read_csv()', 'pd.open_csv()', 'pd.load_csv()', 'pd.csv()'], correct: 0,
    exp: 'pd.read_csv() is the workhorse.' },
  { module: 'pandas', difficulty: 'easy',
    q: 'df.head() returns:',
    options: ['First column', 'First 5 rows', 'Top values', 'Column names'], correct: 1,
    exp: 'First 5 rows by default. Use df.head(10) for more.' },
  { module: 'pandas', difficulty: 'medium',
    q: 'df.loc[0:3] returns how many rows?',
    options: ['3', '4', '5', 'Depends'], correct: 1,
    exp: 'loc is INCLUSIVE on both ends: 0,1,2,3 = 4 rows.' },
  { module: 'pandas', difficulty: 'medium',
    q: 'Correct way to filter age > 25 AND salary > 50000?',
    options: ['df.age > 25 and df.salary > 50000', '(df.age>25) & (df.salary>50000)', 'df.age>25 && df.salary>50000', 'df.filter(age>25)'], correct: 1,
    exp: 'Use & not "and". And parenthesize each condition.' },
  { module: 'pandas', difficulty: 'medium',
    q: 'Which join keeps ALL rows from BOTH DataFrames?',
    options: ['inner', 'left', 'right', 'outer'], correct: 3,
    exp: 'Outer = union. Keeps everything, fills missing with NaN.' },
  { module: 'pandas', difficulty: 'hard',
    q: 'What is groupby().transform("mean") good for?',
    options: ['One row per group', 'Same shape as df — fill with group mean', 'Single value', 'A pivot table'], correct: 1,
    exp: 'transform() returns same shape as original — each row gets its group\'s value.' },

  // ===== CLEANING =====
  { module: 'cleaning', difficulty: 'easy',
    q: 'Which method drops rows with ANY missing values?',
    options: ['df.dropna()', 'df.fillna()', 'df.delete()', 'df.remove()'], correct: 0,
    exp: 'dropna() removes rows with at least one NaN by default.' },
  { module: 'cleaning', difficulty: 'easy',
    q: 'Best way to fill 5% missing in "salary" (randomly missing)?',
    options: ['Drop column', 'Fill with 0', 'Fill with median', 'Leave NaN'], correct: 2,
    exp: 'Median is robust to outliers. Safe for low % random missingness.' },
  { module: 'cleaning', difficulty: 'medium',
    q: 'IQR outlier rule uses what threshold?',
    options: ['mean ± 1 std', 'mean ± 2 std', 'Q1 - 1.5·IQR / Q3 + 1.5·IQR', 'Top/bottom 1%'], correct: 2,
    exp: 'Tukey\'s fence: outside [Q1 - 1.5·IQR, Q3 + 1.5·IQR] is an outlier.' },
  { module: 'cleaning', difficulty: 'medium',
    q: 'Missing values from high earners refusing to disclose are:',
    options: ['MCAR', 'MAR', 'MNAR', 'Random'], correct: 2,
    exp: 'MNAR — missingness depends on the value itself. Hardest type.' },
  { module: 'cleaning', difficulty: 'hard',
    q: 'You have 6,000/10,000 rows missing the "deck" column. Best action?',
    options: ['Fill with mode', 'Forward fill', 'Drop the column', 'KNN impute'], correct: 2,
    exp: '60% missing = imputing fabricates data. Drop and document.' },

  // ===== VIZ =====
  { module: 'viz', difficulty: 'easy',
    q: 'Which chart is BEST for comparing categories?',
    options: ['Pie chart', 'Bar chart', 'Line chart', 'Scatter'], correct: 1,
    exp: 'Bars are precise. Pies force angle comparison — humans are bad at that.' },
  { module: 'viz', difficulty: 'easy',
    q: 'Which library is built ON TOP of Matplotlib?',
    options: ['Plotly', 'Bokeh', 'Seaborn', 'D3'], correct: 2,
    exp: 'Seaborn wraps Matplotlib with prettier defaults and statistical helpers.' },
  { module: 'viz', difficulty: 'medium',
    q: 'Anscombe\'s Quartet teaches us:',
    options: ['Always use 4 datasets', 'Stats alone can mislead — always plot', 'Quartets are best', 'Use 11 data points'], correct: 1,
    exp: 'Same stats can hide totally different shapes. Always plot.' },
  { module: 'viz', difficulty: 'medium',
    q: 'A boxplot shows all EXCEPT:',
    options: ['Median', 'Quartiles', 'Outliers', 'Mean'], correct: 3,
    exp: 'Boxplot: median, quartiles, whiskers, outliers. Mean is NOT shown by default.' },
  { module: 'viz', difficulty: 'medium',
    q: 'Best chart to see CORRELATIONS between many variables?',
    options: ['Pie chart', 'Heatmap', 'Bar chart', 'Histogram'], correct: 1,
    exp: 'Correlation heatmap. Annotate with values, center on 0, use diverging palette.' },
  { module: 'viz', difficulty: 'hard',
    q: 'Why is "viridis" better than "rainbow" colormap?',
    options: ['Looks prettier', 'Perceptually uniform + colorblind-friendly', 'More colors', 'Faster'], correct: 1,
    exp: 'Viridis maps equal data steps to equal visual steps. Rainbow distorts perception.' },

  // ===== STATS =====
  { module: 'stats', difficulty: 'easy',
    q: 'Which is most robust to outliers?',
    options: ['Mean', 'Median', 'Range', 'Sum'], correct: 1,
    exp: 'Median is the middle value — outliers don\'t move it.' },
  { module: 'stats', difficulty: 'easy',
    q: 'In a normal distribution, ~68% of values fall within how many standard deviations?',
    options: ['0.5', '1', '2', '3'], correct: 1,
    exp: '68-95-99.7 rule: ±1σ = 68%.' },
  { module: 'stats', difficulty: 'medium',
    q: 'p-value of 0.03 with α=0.05 means:',
    options: ['H₀ is true', 'Fail to reject H₀', 'Reject H₀', 'Inconclusive'], correct: 2,
    exp: 'p < α → reject H₀. But doesn\'t mean H₀ is FALSE — just unlikely given data.' },
  { module: 'stats', difficulty: 'medium',
    q: 'Central Limit Theorem says:',
    options: ['All distributions are normal', 'Sample means → normal as n grows', 'Mean is always center', 'Sample size doesn\'t matter'], correct: 1,
    exp: 'Sample means become approximately normal as n grows (rule: n ≥ 30).' },
  { module: 'stats', difficulty: 'medium',
    q: 'Correlation r = -0.85 indicates:',
    options: ['No relationship', 'Weak positive', 'Strong negative', 'Strong positive'], correct: 2,
    exp: '|r| big = strong. Minus = inverse.' },
  { module: 'stats', difficulty: 'hard',
    q: 'Type I error means:',
    options: ['False positive (reject true H₀)', 'False negative', 'Sample size error', 'Calculation error'], correct: 0,
    exp: 'Type I = cry wolf. Type II = miss real effect.' },

  // ===== ML =====
  { module: 'ml', difficulty: 'easy',
    q: 'Predicting a continuous number is:',
    options: ['Classification', 'Regression', 'Clustering', 'Reduction'], correct: 1,
    exp: 'Continuous output = regression. Categorical = classification.' },
  { module: 'ml', difficulty: 'easy',
    q: 'Predicting spam vs not-spam is:',
    options: ['Regression', 'Classification', 'Clustering', 'RL'], correct: 1,
    exp: 'Two discrete classes = binary classification.' },
  { module: 'ml', difficulty: 'easy',
    q: 'Why split train and test?',
    options: ['Save memory', 'Evaluate on unseen data', 'Convention', 'Speed'], correct: 1,
    exp: 'Test set simulates "future, unseen" data. Training-accuracy lies.' },
  { module: 'ml', difficulty: 'medium',
    q: 'Train 100%, test 60% accuracy — what is this?',
    options: ['Underfitting', 'Overfitting', 'Just right', 'Broken'], correct: 1,
    exp: 'Memorized training, failed to generalize = overfitting.' },
  { module: 'ml', difficulty: 'medium',
    q: 'For imbalanced cancer data (95% healthy), accuracy of 95% means:',
    options: ['Excellent', 'Could just predict "healthy" always', 'Definitely good', 'More data'], correct: 1,
    exp: 'A trivial "always healthy" model gets 95% and zero cancer detection. Use F1/ROC-AUC.' },
  { module: 'ml', difficulty: 'medium',
    q: 'K-Means is:',
    options: ['Classification', 'Regression', 'Unsupervised clustering', 'Reinforcement'], correct: 2,
    exp: 'Groups data into K clusters without labels.' },
  { module: 'ml', difficulty: 'hard',
    q: 'R² = 0.85 in regression means:',
    options: ['Predictions are 85% accurate', '85% of variance in y is explained', 'p-value = 0.85', 'Error = 15%'], correct: 1,
    exp: 'R² = proportion of variance explained. 1=perfect, 0=no better than predicting the mean.' },
  { module: 'ml', difficulty: 'hard',
    q: 'ROC-AUC = 0.5 means:',
    options: ['Perfect', 'Random guessing', 'Half correct', 'Inverted'], correct: 1,
    exp: 'AUC 0.5 = no better than coin flip. 1.0 = perfect.' }
];

function getQuestionsForModule(moduleKey) {
  if (!moduleKey || moduleKey === 'all') return [...QUESTIONS];
  return QUESTIONS.filter(q => q.module === moduleKey);
}

function getRandomQuestions(count, moduleKey = null) {
  const pool = getQuestionsForModule(moduleKey);
  const shuffled = pool.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

function moduleCounts() {
  const out = {};
  Object.keys(MODULES).forEach(k => {
    out[k] = QUESTIONS.filter(q => q.module === k).length;
  });
  return out;
}

module.exports = {
  MODULES,
  QUESTIONS,
  getQuestionsForModule,
  getRandomQuestions,
  moduleCounts
};
