// =====================================================
//   Template Quizzes
//   These ship with the app. Staff can add custom quizzes
//   on top via the /create.html UI.
// =====================================================

const PYTHON_QUIZ = {
  id: 'tpl-python',
  title: 'Python Programming',
  description: 'Test your Python fundamentals — variables, data types, lists, dicts, loops, functions, OOP',
  emoji: '🐍',
  color: 'linear-gradient(135deg, #3776AB, #FFD43B)',
  isTemplate: true,
  questions: [
    { difficulty: 'easy',
      q: 'How do you create a list in Python?',
      options: ['list = (1, 2, 3)', 'list = [1, 2, 3]', 'list = {1, 2, 3}', 'list = <1, 2, 3>'],
      correct: 1,
      exp: 'Square brackets [] create a list. () is a tuple, {} is a set or dict.' },
    { difficulty: 'easy',
      q: 'What is the output of len("Python")?',
      options: ['5', '6', '7', 'Error'],
      correct: 1,
      exp: '"Python" has 6 characters: P, y, t, h, o, n.' },
    { difficulty: 'easy',
      code: 'x = [1, 2, 3]\nx.append(4)\nprint(x)',
      q: 'What is printed?',
      options: ['[1, 2, 3]', '[1, 2, 3, 4]', '[4, 1, 2, 3]', '4'],
      correct: 1,
      exp: 'append() adds the element to the end and modifies the list in place.' },
    { difficulty: 'easy',
      q: 'Which is NOT a valid Python data type?',
      options: ['int', 'float', 'char', 'str'],
      correct: 2,
      exp: 'Python has no separate char type — single characters are just strings of length 1.' },
    { difficulty: 'medium',
      code: 'nums = [1, 2, 3, 4, 5]\nprint(nums[1:4])',
      q: 'What is the output?',
      options: ['[1, 2, 3]', '[2, 3, 4]', '[2, 3, 4, 5]', '[1, 2, 3, 4]'],
      correct: 1,
      exp: 'Slicing [start:stop] — start is inclusive, stop is exclusive. [1:4] gives indices 1, 2, 3.' },
    { difficulty: 'medium',
      code: 'd = {"a": 1, "b": 2}\nprint(d.get("c", 99))',
      q: 'What is the output?',
      options: ['None', 'KeyError', '99', '0'],
      correct: 2,
      exp: 'dict.get(key, default) returns the default value if the key is missing — safer than d[key].' },
    { difficulty: 'medium',
      q: 'Which collection allows ONLY UNIQUE elements?',
      options: ['list', 'tuple', 'set', 'dict'],
      correct: 2,
      exp: 'Sets automatically remove duplicates. set([1,1,2,2,3]) → {1, 2, 3}.' },
    { difficulty: 'medium',
      code: 'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)',
      q: 'What is printed?',
      options: ['[1, 2, 3]', '[1, 2, 3, 4]', '[4]', 'Error'],
      correct: 1,
      exp: 'b = a does NOT copy — both names point to the same list. Use a.copy() or list(a).' },
    { difficulty: 'medium',
      code: 'for i in range(2, 8, 2):\n    print(i, end=" ")',
      q: 'What prints?',
      options: ['2 4 6', '2 4 6 8', '2 3 4 5 6 7', '0 2 4 6'],
      correct: 0,
      exp: 'range(start, stop, step). start=2, stop=8 (exclusive), step=2 → 2, 4, 6.' },
    { difficulty: 'medium',
      q: 'What does the "is" operator check?',
      options: ['Equality of values', 'Equality of types', 'Same object identity', 'String comparison'],
      correct: 2,
      exp: '"is" checks identity (same object in memory). "==" checks value equality.' },
    { difficulty: 'medium',
      code: 'x = "hello"\nprint(x[::-1])',
      q: 'What is the output?',
      options: ['hello', 'olleh', 'h', 'Error'],
      correct: 1,
      exp: '[::-1] reverses the sequence using slicing with step -1.' },
    { difficulty: 'hard',
      code: 'sq = [x**2 for x in range(5) if x % 2 == 0]\nprint(sq)',
      q: 'What is the output?',
      options: ['[0, 1, 4, 9, 16]', '[0, 4, 16]', '[1, 9]', '[2, 4]'],
      correct: 1,
      exp: 'List comprehension with filter: keep even x (0, 2, 4), then square → [0, 4, 16].' },
    { difficulty: 'hard',
      code: 'def add(a, b=[]):\n    b.append(a)\n    return b\n\nprint(add(1))\nprint(add(2))',
      q: 'What is the output?',
      options: ['[1] then [2]', '[1] then [1, 2]', 'Error', '[1, 2] both times'],
      correct: 1,
      exp: 'Mutable default arguments — the list is shared between calls. Classic Python gotcha.' },
    { difficulty: 'hard',
      q: 'What does *args allow in a function definition?',
      options: ['Type checking', 'Variable number of positional arguments', 'Keyword arguments only', 'Async execution'],
      correct: 1,
      exp: '*args lets you pass any number of positional args. **kwargs does the same for keyword args.' },
    { difficulty: 'hard',
      code: 'try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print("A")\nexcept Exception:\n    print("B")\nfinally:\n    print("C")',
      q: 'What is the output?',
      options: ['A', 'A then C', 'B then C', 'C only'],
      correct: 1,
      exp: 'ZeroDivisionError matches first → prints A. finally always runs → prints C.' },
    { difficulty: 'medium',
      q: 'Which keyword defines a class in Python?',
      options: ['def', 'class', 'object', 'struct'],
      correct: 1,
      exp: '"class ClassName:" defines a class. def defines functions.' },
    { difficulty: 'medium',
      q: 'What does __init__ method do?',
      options: ['Destroys an object', 'Initializes a new object (constructor)', 'Imports a module', 'Defines static methods'],
      correct: 1,
      exp: '__init__ is the constructor — runs when you create a new instance of the class.' },
    { difficulty: 'medium',
      q: 'What is the correct way to open a file safely?',
      options: ['open("file.txt")', 'with open("file.txt") as f:', 'file.open("file.txt")', 'fopen("file.txt")'],
      correct: 1,
      exp: 'The "with" statement (context manager) auto-closes the file even if an error occurs.' },
    { difficulty: 'hard',
      q: 'What is the time complexity of looking up a value in a dict?',
      options: ['O(n)', 'O(log n)', 'O(1) average', 'O(n²)'],
      correct: 2,
      exp: 'Dicts use hash tables — O(1) average case. O(n) worst case (with hash collisions).' },
    { difficulty: 'hard',
      code: 'def foo():\n    yield 1\n    yield 2\n    yield 3\n\ng = foo()\nprint(next(g))\nprint(next(g))',
      q: 'What is printed?',
      options: ['1 then 2', '1 then 1', '2 then 3', 'Error'],
      correct: 0,
      exp: 'Generators yield one value at a time. Each next() call resumes execution until the next yield.' }
  ]
};

const DSA_JAVA_QUIZ = {
  id: 'tpl-dsa-java',
  title: 'DSA in Java',
  description: 'Data structures and algorithms in Java — arrays, lists, stacks, trees, hashing, complexity',
  emoji: '☕',
  color: 'linear-gradient(135deg, #007396, #ED8B00)',
  isTemplate: true,
  questions: [
    { difficulty: 'easy',
      q: 'Which keyword in Java is used to inherit a class?',
      options: ['inherits', 'extends', 'implements', 'derives'],
      correct: 1,
      exp: '"extends" is for class inheritance. "implements" is for interfaces.' },
    { difficulty: 'easy',
      q: 'What is the time complexity to access an element by index in an array?',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
      correct: 0,
      exp: 'Arrays support random access in constant time via index arithmetic.' },
    { difficulty: 'easy',
      q: 'Which Java collection allows duplicate elements?',
      options: ['HashSet', 'TreeSet', 'ArrayList', 'LinkedHashSet'],
      correct: 2,
      exp: 'Lists allow duplicates. Sets do not. ArrayList is the most common.' },
    { difficulty: 'easy',
      q: 'Stack follows which order?',
      options: ['FIFO (First In First Out)', 'LIFO (Last In First Out)', 'Random', 'Sorted'],
      correct: 1,
      exp: 'Stack = LIFO. Last pushed element is the first popped.' },
    { difficulty: 'easy',
      q: 'Queue follows which order?',
      options: ['LIFO', 'FIFO', 'Sorted', 'Random'],
      correct: 1,
      exp: 'Queue = FIFO. First enqueued element is the first dequeued.' },
    { difficulty: 'medium',
      q: 'What is the average time complexity of HashMap.get()?',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
      correct: 0,
      exp: 'HashMap uses a hash function — O(1) average, O(n) worst case with many collisions.' },
    { difficulty: 'medium',
      q: 'Which sorting algorithm has O(n log n) average and O(n²) worst case?',
      options: ['Merge Sort', 'Quick Sort', 'Bubble Sort', 'Counting Sort'],
      correct: 1,
      exp: 'Quick Sort is O(n log n) average but degrades to O(n²) on already-sorted input without random pivots.' },
    { difficulty: 'medium',
      code: 'Stack<Integer> s = new Stack<>();\ns.push(1); s.push(2); s.push(3);\nSystem.out.println(s.pop() + " " + s.peek());',
      q: 'What is the output?',
      options: ['1 2', '3 2', '3 3', '1 3'],
      correct: 1,
      exp: 'pop() returns and removes top (3). peek() returns top without removing — now 2.' },
    { difficulty: 'medium',
      q: 'In a Binary Search Tree, where are values smaller than the root stored?',
      options: ['Right subtree', 'Left subtree', 'Anywhere', 'Both subtrees'],
      correct: 1,
      exp: 'BST property: left subtree has values less than root, right subtree has values greater.' },
    { difficulty: 'medium',
      q: 'What is the time complexity of binary search?',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
      correct: 1,
      exp: 'Binary search halves the search space each step → O(log n). Requires sorted array.' },
    { difficulty: 'medium',
      code: 'LinkedList<Integer> ll = new LinkedList<>();\nll.add(1); ll.add(2); ll.addFirst(0);\nSystem.out.println(ll);',
      q: 'What is printed?',
      options: ['[1, 2, 0]', '[0, 1, 2]', '[2, 1, 0]', '[1, 0, 2]'],
      correct: 1,
      exp: 'addFirst(0) puts 0 at the head. add() appends to the tail. Final order: 0, 1, 2.' },
    { difficulty: 'medium',
      q: 'Which traversal of a BST gives nodes in sorted order?',
      options: ['Preorder', 'Inorder', 'Postorder', 'Level order'],
      correct: 1,
      exp: 'Inorder (left → root → right) visits a BST in ascending order.' },
    { difficulty: 'hard',
      q: 'A complete binary tree with n nodes has what height?',
      options: ['O(n)', 'O(log n)', 'O(√n)', 'O(n log n)'],
      correct: 1,
      exp: 'Complete binary tree with n nodes has height ⌊log₂ n⌋ → O(log n).' },
    { difficulty: 'hard',
      q: 'Which data structure is best for implementing recursion?',
      options: ['Queue', 'Stack', 'Heap', 'Tree'],
      correct: 1,
      exp: 'Function call stack uses LIFO — Stack. That\'s why deep recursion causes StackOverflowError.' },
    { difficulty: 'hard',
      q: 'What is the worst-case time complexity of Merge Sort?',
      options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
      correct: 1,
      exp: 'Merge Sort is O(n log n) in all cases. Stable, but O(n) extra space.' },
    { difficulty: 'hard',
      q: 'In Java, which interface should you implement to make objects comparable?',
      options: ['Iterable', 'Comparator', 'Comparable', 'Collection'],
      correct: 2,
      exp: 'Comparable defines compareTo() for natural ordering. Comparator is for external comparison logic.' },
    { difficulty: 'hard',
      code: 'int[] a = {3, 1, 4, 1, 5, 9, 2, 6};\nArrays.sort(a);\nSystem.out.println(Arrays.binarySearch(a, 5));',
      q: 'What is printed?',
      options: ['4', '5', '-1', '3'],
      correct: 0,
      exp: 'After sorting: [1, 1, 2, 3, 4, 5, 6, 9]. binarySearch finds 5 at index 5... wait — 1,1,2,3,4,5 → index 5. Actually: [1(0), 1(1), 2(2), 3(3), 4(4), 5(5)]. Hmm, but the answer is 4? Re-count: sorted is [1,1,2,3,4,5,6,9]. 5 is at index 5. But the question may have different values. The expected answer for the listed options is 4 — typical for similar questions. The student should verify by counting.',
    },
    { difficulty: 'hard',
      q: 'Which graph traversal uses a queue?',
      options: ['DFS', 'BFS', 'Topological sort', 'Both DFS and BFS'],
      correct: 1,
      exp: 'BFS uses a queue (FIFO) to explore neighbors level by level. DFS uses a stack (or recursion).' },
    { difficulty: 'medium',
      q: 'Which Java collection maintains insertion order AND uniqueness?',
      options: ['HashSet', 'TreeSet', 'LinkedHashSet', 'ArrayList'],
      correct: 2,
      exp: 'LinkedHashSet preserves insertion order and disallows duplicates.' },
    { difficulty: 'hard',
      q: 'What is the space complexity of recursive Fibonacci (naïve)?',
      options: ['O(1)', 'O(n)', 'O(log n)', 'O(2ⁿ)'],
      correct: 1,
      exp: 'O(n) due to recursion depth (call stack). Time complexity is O(2ⁿ).' }
  ]
};

// Fix the binary-search quiz answer — recompute properly
// Sorted [1,1,2,3,4,5,6,9], binarySearch(a, 5) returns index 5.
(function fixBinarySearchAnswer() {
  const q = DSA_JAVA_QUIZ.questions.find(x => x.code && x.code.includes('binarySearch'));
  if (q) {
    q.options = ['4', '5', '-1', '3'];
    q.correct = 1; // index 5 after sorting
    q.exp = 'After sorting: [1, 1, 2, 3, 4, 5, 6, 9]. binarySearch(a, 5) finds 5 at index 5.';
  }
})();

module.exports = { PYTHON_QUIZ, DSA_JAVA_QUIZ, TEMPLATES: [PYTHON_QUIZ, DSA_JAVA_QUIZ] };
